drop table if exists task_domain CASCADE;
drop table if exists to_do_domain CASCADE;
create table task_domain (task_id bigint generated by default as identity, act varchar(255), completed boolean not null, date varchar(255), notes varchar(140), priority integer not null, to_do_id bigint, primary key (task_id));
create table to_do_domain (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table task_domain add constraint FKdp6hsg4fffbm3xq4p4t2153ft foreign key (to_do_id) references to_do_domain on delete cascade;